In [29]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
import pickle

In [30]:
scaler = MaxAbsScaler()

In [31]:
train = pd.read_csv('train.csv')

In [32]:
test = pd.read_csv('test.csv')

In [33]:
train.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0             6000   
1       1        1           0          0              0             2958   
2       1        1           2          0              0             6250   
3       1        1           0          0              0             2083   
4       1        0           0          0              0             4166   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             2250.0       265.0             360.0               1   
1             2900.0       131.0             360.0               1   
2             1695.0       210.0             360.0               1   
3             3150.0       128.0             360.0               1   
4                0.0        98.0             360.0               0   

   Property_Area  Loan_Status  
0              1            0  
1              1            1  
2              1            1  
3              1            1  
4              1            0

In [34]:
train_y = train.iloc[:,-1]

In [35]:
train_x = train.drop('Loan_Status',axis=1)

In [36]:
test_y = test.iloc[:,-1]

In [37]:
test_x = test.drop('Loan_Status',axis=1)

In [38]:
x = pd.concat([train_x,test_x],axis=0)
y = pd.concat([train_y,test_y],axis=0)

In [39]:
train_x = scaler.fit_transform(train_x)

In [40]:
test_x = scaler.fit_transform(test_x)

# DecisionTree

In [41]:
def decisionTree(train_x,test_x,train_y,test_y):
    dt = DecisionTreeClassifier()
    dt.fit(train_x,train_y)
    y_pred = dt.predict(test_x)
    print("**** Decision Tree Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# RandomForest

In [42]:
def randomForest(train_x,test_x,train_y,test_y):
    rf = RandomForestClassifier()
    rf.fit(train_x,train_y)
    y_pred = rf.predict(test_x)
    print("**** Random Forest Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# Knn

In [43]:
def knn(train_x,test_x,train_y,test_y):
    knn = KNeighborsClassifier()
    knn.fit(train_x,train_y)
    y_pred = knn.predict(test_x)
    print("**** KNeighbour Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# xgboost

In [44]:
def xgboost(train_x,test_x,train_y,test_y):
    xg = GradientBoostingClassifier()
    xg.fit(train_x,train_y)
    y_pred = xg.predict(test_x)
    print("**** Gradient Boosting Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

# Comparing The Models

In [45]:
decisionTree(train_x,test_x,train_y,test_y)

**** Decision Tree Classifier ****
Confusion Matrix
[[31 12]
 [27 53]]
Classification Report
              precision    recall  f1-score   support

           0       0.53      0.72      0.61        43
           1       0.82      0.66      0.73        80

    accuracy                           0.68       123
   macro avg       0.67      0.69      0.67       123
weighted avg       0.72      0.68      0.69       123



In [46]:
randomForest(train_x,test_x,train_y,test_y)

**** Random Forest Classifier ****
Confusion Matrix
[[23 20]
 [ 8 72]]
Classification Report
              precision    recall  f1-score   support

           0       0.74      0.53      0.62        43
           1       0.78      0.90      0.84        80

    accuracy                           0.77       123
   macro avg       0.76      0.72      0.73       123
weighted avg       0.77      0.77      0.76       123



In [47]:
knn(train_x,test_x,train_y,test_y)

**** KNeighbour Classifier ****
Confusion Matrix
[[18 25]
 [ 3 77]]
Classification Report
              precision    recall  f1-score   support

           0       0.86      0.42      0.56        43
           1       0.75      0.96      0.85        80

    accuracy                           0.77       123
   macro avg       0.81      0.69      0.70       123
weighted avg       0.79      0.77      0.75       123



In [48]:
xgboost(train_x,test_x,train_y,test_y)

**** Gradient Boosting Classifier ****
Confusion Matrix
[[24 19]
 [16 64]]
Classification Report
              precision    recall  f1-score   support

           0       0.60      0.56      0.58        43
           1       0.77      0.80      0.79        80

    accuracy                           0.72       123
   macro avg       0.69      0.68      0.68       123
weighted avg       0.71      0.72      0.71       123



In [49]:
rf = RandomForestClassifier()
rf.fit(train_x,train_y)
ypred = rf.predict(test_x)

In [50]:
f1_score(ypred,test_y,average='weighted')

0.7763625723991818

In [51]:
cv = cross_val_score(rf,x,y,cv=5)

In [52]:
np.mean(cv)

0.7882846861255498

In [53]:
import joblib
joblib.dump(rf,'model.pkl')

['model.pkl']